// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ESP_Custom_Libraries","status":true,"description":"","parameters":{}},
{"name":"ESP_Vector3","status":true,"description":"","parameters":{}},
{"name":"ESP_All_Important_Code_Here","status":true,"description":"","parameters":{}},
{"name":"ESP_Data_And_Saves_And_Such","status":true,"description":"","parameters":{}},
{"name":"ESP_Animated_Sprite","status":true,"description":"","parameters":{}},
{"name":"ESP_Player_Sprite_Stuff","status":true,"description":"","parameters":{}},
{"name":"ESP_Player_Guy_Stuff","status":true,"description":"","parameters":{}},
{"name":"ESP_Tilemap_Manipulation","status":true,"description":"","parameters":{}},
{"name":"ESP_Input_Thingies","status":true,"description":"","parameters":{}},
{"name":"ESP_Put_This_Last_On_Plugin_List","status":true,"description":"","parameters":{}}
];
